# Generated by Django 2.2.3 on 2019-07-14 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flight',
            new_name='Flights',
        ),
    ]
